name: Build Kivy Android APK

on:
  push:
    branches:
      # Trigger the workflow whenever code is pushed to the 'main' branch
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest # GitHub's runner machine (Linux)

    steps:
      # Step 1: Checks out a copy of your repository on the runner machine
      - uses: actions/checkout@v4

      # Step 2: Uses the specialized Buildozer action
      - name: Set up Buildozer and Build APK
        uses: kottman/action-buildozer@v1
        with:
          command: buildozer android debug

      # Step 3: Archives the resulting APK file
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          # The APK file is generated in the 'bin' folder
          path: bin/*.apk
