name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    name: Build APK for Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- NEW STEP TO INSTALL BUILDER DEPENDENCIES MANUALLY ---
      - name: Install Buildozer and Cython dependencies (PEP 668 Fix)
        run: |
          # Install Buildozer and Cython, forcing the installation to bypass PEP 668 error
          pip install --break-system-packages buildozer cython==0.29.33

      # Step 2: Build the APK using the Buildozer action
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          # IMPORTANT: Set buildozer_version to empty to skip internal installation
          buildozer_version: '' 
        env:
          # Fix for the previous 'chown' error
          USER: root 

      # Step 3: Upload the resulting APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dicom-viewer-apk
          path: ${{ steps.buildozer.outputs.filename }}
