name: Build Kivy APK

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.36

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DICOM-APK
          path: bin/*.apk
