name: Build Kivy Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    name: Build APK for Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Build the APK using the maintained Buildozer action
      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable
        # 🐛 THE FIX IS HERE 🐛
        env:
          # This variable tells the action to run as root, bypassing the 'chown' error.
          # The 'user' variable is what the script is failing to resolve.
          USER: root 
          
      # Step 3: Upload the resulting APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dicom-viewer-apk
          path: ${{ steps.buildozer.outputs.filename }}
